#!/bin/sh
uci set wireless.@wifi-device[0].country='CN'
uci set wireless.@wifi-device[0].htmode='HT40'
uci set wireless.@wifi-device[0].channel='6'
uci set wireless.@wifi-device[0].noscan='1'
uci set wireless.@wifi-device[1].country='CN'
uci set wireless.@wifi-device[1].htmode='VHT80'
uci set wireless.@wifi-device[1].channel='149'
uci set wireless.@wifi-iface[0].ssid='Newifi_D2_2.4G'
uci set wireless.@wifi-iface[0].encryption='psk-mixed+ccmp'
uci set wireless.@wifi-iface[0].key='123456aA'
uci set wireless.@wifi-iface[1].ssid='Newifi_D2_5G'
uci set wireless.@wifi-iface[1].encryption='psk-mixed+ccmp'
uci set wireless.@wifi-iface[1].key='123456aA'
uci set network.wan.peerdns='0'
uci add_list network.wan.dns='223.5.5.5'
uci add_list network.wan.dns='114.114.114.114'
uci set system.@system[-1].zonename='Asia/Shanghai'
uci set system.@system[-1].timezone='CST-8'
uci set system.@system[-1].hostname='Newifi-D2'
uci commit
/etc/init.d/network restart
/etc/init.d/system restart
exit 0
