#!/bin/sh
# curl --connect-timeout 15 'https://raw.githubusercontent.com/zcy85611/dnsmasq_rules/main/chinalist%2Beasylist.conf' > /etc/dnsmasq.d/chinalist+easylist.conf
# curl --connect-timeout 15 'https://raw.githubusercontent.com/zcy85611/dnsmasq_rules/main/cjxlist.conf' > /etc/dnsmasq.d/cjxlist.conf
curl --connect-timeout 15 'https://raw.githubusercontent.com/zcy85611/dnsmasq_rules/main/gfwlist.conf' > /tmp/gfwlist.conf
if [ $(du /tmp/gfwlist.conf|awk '{print $1}') -gt 150 ];
then
	mv -f /tmp/gfwlist.conf /etc/dnsmasq.d
fi
/etc/init.d/dnsmasq restart
