#!/bin/sh
chmod +x -R /etc/scripts/*
chmod +x -R /etc/init.d/*
echo "public:$(openssl passwd 123456)" >/etc/nginx/webdavpasswd
echo "conf-dir=/etc/dnsmasq.d" >> /etc/dnsmasq.conf
uci set firewall.@defaults[0].flow_offloading='1'
uci set firewall.@defaults[0].flow_offloading_hw='1'
uci add firewall rule 
uci set firewall.@rule[-1].name="Allow Aliyun SSL"
uci set firewall.@rule[-1].family="ipv6"
uci set firewall.@rule[-1].src="wan"
uci set firewall.@rule[-1].dest_port="31667"
uci set firewall.@rule[-1].target="ACCEPT"
uci add firewall rule 
uci set firewall.@rule[-1].name="Allow Webdav SSL"
uci set firewall.@rule[-1].family="ipv6"
uci set firewall.@rule[-1].src="wan"
uci set firewall.@rule[-1].dest_port="31668"
uci set firewall.@rule[-1].target="ACCEPT"
uci delete nginx._redirect2ssl.return='302 https://$host$request_uri'
uci add_list nginx._redirect2ssl.include='restrict_locally'
uci add_list nginx._redirect2ssl.include='conf.d/*.locations'
uci set nginx._redirect2ssl.access_log='off'
uci commit
/etc/init.d/firewall restart
/etc/init.d/dnsmasq restart
/etc/init.d/nginx reload
/etc/init.d/p910nd disable
/etc/init.d/nfsd disable
/etc/init.d/wireguard disable
/etc/init.d/aria2 disable
exit 0
