#!/bin/sh
uci set network.wan.peerdns='0'
uci add_list network.wan.dns='223.5.5.5'
uci add_list network.wan.dns='114.114.114.114'
uci set system.@system[-1].zonename='Asia/Shanghai'
uci set system.@system[-1].timezone='CST-8'
uci set system.@system[-1].hostname='R2S'
uci commit
/etc/init.d/network restart
/etc/init.d/system restart
exit 0
