#!/bin/sh /etc/rc.common
# "new(er)" style init script
# Look at /lib/functions/service.sh on a running system for explanations of what other SERVICE_
# options you can use, and when you might want them.

START=99

SERVICE_USE_PID=1
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

start() {
ulimit -n 100000
ip rule add fwmark 1 table 100
ip route add default via $(ip route|awk '$1=="default" {print $3}') table 100
ifup wg0
iptables -t mangle -N wireguard
iptables -t mangle -A wireguard -m set --match-set forceproxy dst -j RETURN
iptables -t mangle -A wireguard -m set --match-set gfwlist dst -j RETURN
iptables -t mangle -A wireguard -m set --match-set Cloudflare dst -j RETURN
iptables -t mangle -A wireguard -m set --match-set China dst -j MARK --set-mark 1
iptables -t mangle -A PREROUTING -j wireguard
iptables -t mangle -A OUTPUT -j wireguard
}

stop() {
ifdown wg0
iptables -t mangle -D PREROUTING -j wireguard
iptables -t mangle -D OUTPUT -j wireguard
iptables -t mangle -F wireguard
iptables -t mangle -X wireguard
ip route add default via $(ip route list table 100|awk '$2=="via" {print $3}')
ip route flush table 100
ip rule del table 100
}
