# This is free software, licensed under the MIT License.
# See /LICENSE for more information.

name: Path_Test

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Checkout
      run: |
        pwd
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        ls
        cd /
        ls
        
    - name: PWD Test
      working-directory: /workdir
      run: |
        pwd
        ls
        cd $GITHUB_WORKSPACE
        pwd
        ls
